# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'inke' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for inke

  target 'inkeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'inkeUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SDWebImage', '~> 3.8.1'
pod 'AFNetworking', '~> 3.1.0'
pod 'MJExtension'
pod 'YYKit'
pod 'Masonry'


end
